#!/usr/bin/env node
// Détecte les marques d'IA dans un projet : trailers de commit, fichiers d'outils IA,
// mentions dans le contenu (français et anglais). Cross-platform (Node + git). Lecture seule.
// Usage : node scripts/scan-ia.js [chemin]   (défaut : répertoire courant)
"use strict";
const { execFileSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const root = process.argv[2] || ".";
let found = 0;
const Y = "\x1b[33m", R = "\x1b[0m";
const hit = (m) => { console.log(`  ${Y}!${R} ${m}`); found = 1; };
const git = (args) => {
  try { return execFileSync("git", args, { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }); }
  catch { return ""; }
};

const contentRe = /chatgpt|gpt-[0-9]|as an ai|language model|copilot|generated by (ai|claude)|claude code|genere par (l.?ia|claude)|généré par (l.?ia|claude)|ecrit par claude|écrit par claude|en tant qu.?(ia|intelligence artificielle)|modele de langage|modèle de langage/i;

console.log("Scan des marques d'IA — " + path.resolve(root));

const isGit = git(["rev-parse", "--is-inside-work-tree"]).trim() === "true";

if (isGit) {
  const log = git(["log", "--all", "-i", "--grep=Co-authored-by: Claude", "--grep=Generated with", "--grep=anthropic.com", "--grep=\u{1F916}", "--pretty=oneline"]);
  const n = log.split("\n").filter(Boolean).length;
  if (n > 0) hit(`${n} commit(s) avec une marque IA dans le message ou le trailer`);
  const authors = git(["log", "--all", "--pretty=%an <%ae>%n%cn <%ce>"]);
  if (/anthropic\.com|noreply@anthropic|<claude@/i.test(authors)) hit("auteur/committer Anthropic dans l'historique");
}

["CLAUDE.md", ".claude", ".cursor", ".cursorrules", ".aider.conf.yml", ".aiderignore", ".github/copilot-instructions.md"].forEach((f) => {
  if (fs.existsSync(path.join(root, f))) hit("fichier/dossier d'outil IA présent : " + f);
});

// Contenu : on parcourt les fichiers suivis par git (respecte donc .gitignore).
const matches = [];
if (isGit) {
  const tracked = git(["ls-files"]).split("\n").filter(Boolean);
  for (const f of tracked) {
    if (matches.length >= 20) break;
    let txt;
    try { txt = fs.readFileSync(path.join(root, f), "utf8"); } catch { continue; }
    const lines = txt.split("\n");
    for (let i = 0; i < lines.length && matches.length < 20; i++) {
      if (contentRe.test(lines[i])) matches.push(`${f}:${i + 1}:${lines[i].trim()}`);
    }
  }
}
if (matches.length) { hit("mentions d'IA dans le contenu (à vérifier) :"); matches.forEach((m) => console.log("      " + m)); }

console.log("");
console.log(found === 0 ? "Aucune marque d'IA évidente." : "Marques détectées — lance /sans-ia pour nettoyer.");
process.exit(found);
