#!/usr/bin/env bash
# Détecte les marques d'IA dans un projet : trailers de commit, fichiers d'outils IA,
# mentions dans le contenu. Lecture seule, ne modifie rien.
# Usage : scripts/scan-ia.sh [chemin]   (défaut : répertoire courant)
set -uo pipefail

root="${1:-.}"
cd "$root" || exit 1

found=0
hit() { printf "  \033[33m!\033[0m %s\n" "$1"; found=1; }

echo "Scan des marques d'IA — $(pwd)"

# 1. Historique git : trailers et signatures
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  ai_commits=$(git log --all -i \
    --grep='Co-authored-by: Claude' \
    --grep='Generated with' \
    --grep='anthropic.com' \
    --grep='🤖' \
    --pretty=oneline 2>/dev/null | wc -l | tr -d ' ' || true)
  [ "${ai_commits:-0}" -gt 0 ] && hit "$ai_commits commit(s) avec une marque IA dans le message ou le trailer"

  ai_authors=$(git log --all --pretty='%an <%ae>%n%cn <%ce>' 2>/dev/null | grep -ciE 'claude|anthropic' || true)
  [ "${ai_authors:-0}" -gt 0 ] && hit "auteur/committer mentionnant Claude/Anthropic dans l'historique"
fi

# 2. Fichiers d'outils IA versionnés
for f in CLAUDE.md .claude .cursor .cursorrules .aider.conf.yml .aiderignore .github/copilot-instructions.md; do
  [ -e "$f" ] && hit "fichier/dossier d'outil IA présent : $f"
done

# 3. Mentions d'IA dans le contenu (candidats — un vrai prénom « Claude » est un faux positif)
matches=$(grep -rniE 'chatgpt|gpt-[0-9]|as an ai|language model|generated by (ai|claude)|claude code|copilot' \
  --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=.venv --exclude-dir=dist --exclude-dir=build \
  . 2>/dev/null | head -20 || true)
if [ -n "$matches" ]; then
  hit "mentions d'IA dans le contenu (à vérifier) :"
  echo "$matches" | sed 's/^/      /'
fi

echo
if [ "$found" -eq 0 ]; then
  echo "Aucune marque d'IA évidente."
else
  echo "Marques détectées — lance /sans-ia pour nettoyer."
fi
exit "$found"
